### ISSUE TITLE
The application uses wrong jobStore class

### ISSUE THREAD

**Issue by ghost** [ChamithKodikara/quartz-demo#1]
As it is defined in the application.properties it should use
`spring.quartz.properties.org.quartz.jobStore.class=org.quartz.impl.jdbcjobstore.JobStoreTX`

but when running the application it actually uses
`org.quartz.impl.jdbcjobstore.JobStoreCMT`
which does not manage the transactions, so the example fails in a clustered environment.

**Comment by ChamithKodikara** [comment]
@kalverk thanks for finding this i checked the Scheduler Factory initialization and the thing is "spring.quartz.properties.org.quartz.jobStore.class" value get replaced by spring from "JobStoreTX" to "org.springframework.scheduling.quartz.LocalDataSourceJobStore".

https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/scheduling/quartz/LocalDataSourceJobStore.html

I'll look into this more, mean while does this works for u?

**Comment by ghost** [comment]
LocalDataSourceJobStore will fail in clusterised environment with creating/removing triggers.

**Comment by ChamithKodikara** [comment]
@kalverk  What do u mean by fails in clustered environment, correct me if I'm wrong as per my knowledge even in clustered environment no matter how much scheduler instance are running only one node will handle the quartz jobs. I don't think multiple node are executing multiple jobs synchronously. And "LocalDataSourceJobStore " using spring transactions 

"Operations performed by this JobStore will properly participate in any kind of Spring-managed transaction, as it uses Spring's DataSourceUtils connection handling methods that are aware of a current transaction. " - API Doc

**Comment by ghost** [comment]
I was a little misleading in my initial request. 

When you are setting 
`spring.quartz.properties.org.quartz.jobStore.class=org.quartz.impl.jdbcjobstore.JobStoreTX`

It does not get used by spring, since if datasource is set in java `schedulerFactory.setDataSource(dataSource);` Quartz always starts using `LocalDataSourceJobStore `.

Which is not the desired behaviour, since you defined JobStoreTX. In order to still use it you need to define a separate datasource for quartz.

E.g
```
spring.quartz.properties.org.quartz.jobStore.dataSource=myDS
spring.quartz.properties.org.quartz.dataSource.myDS.driver=org.h2.Driver
spring.quartz.properties.org.quartz.dataSource.myDS.URL=jdbc:h2:mem:testdb
spring.quartz.properties.org.quartz.dataSource.myDS.user=sa
spring.quartz.properties.org.quartz.dataSource.myDS.password=
spring.quartz.properties.org.quartz.dataSource.myDS.maxConnections=5
``` 

The clustering problem I mentioned is another issue with quartz and not related to JobStoreTX as I initially thought.
