### ISSUE TITLE
testing broken.

### ISSUE THREAD

**Issue by windbender** [ChamithKodikara/quartz-demo#2]
running "mvn test". should not come to a halt because the system upon which this is run is not configured in some predefined way.

I would suggest either

a). Test are setup to run with H2. an in-jvm-process database which is SQL compliant.

or

b) if you must use a "real" database like Postgres or mysql that you use some one of the "test container" database setups.  In this way all that's needed is docker.  All the other details are "fixed" within your test setup.

**Comment by ChamithKodikara** [comment]
hi windbender,

yeah thanks for this suggestion, actually i haven't any integration or unit testing to this, we can setup Junit and Integration testing with mock db and mock services to do the test scenarios, like u said we could use in-memory h2 db or a MySQL or PostgreSQL db to create tests
